# -*- coding: utf-8 -*-
"""volume_of_sphere.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZLwQn5pkOJTJ9HJt5fx0Sq6EIS6soQwI
"""

import math

def calculate_volume_of_sphere(radius):
    volume = (4 / 3) * math.pi * radius**3
    return volume


radius1 = 30
area1 = calculate_volume_of_sphere(radius1)
print(f"Volume of sphere with radius 30 {radius1} is: {area1}")

radius2 = 40
area2 = calculate_volume_of_sphere(radius2)
print(f"Volume of sphere with radius 40 {radius2} is: {area2}")